/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio15;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Aarón
 */
public class PanelCartas extends javax.swing.JFrame implements ActionListener {

    private JPanel cardPanel;
    private CardLayout cardLayout;

    /**
     * Creates new form NewJFrame
     */
    public PanelCartas() {
        initComponents();

        // Crear el panel para el CardLayout
        cardPanel = new JPanel();
        cardLayout = new CardLayout();
        cardPanel.setLayout(cardLayout);

        JPanel card1 = new JPanel();
        card1.setBackground(Color.RED);
        JPanel card2 = new JPanel();
        card2.setBackground(Color.GREEN);
        JPanel card3 = new JPanel();
        card3.setBackground(Color.BLUE);

        cardPanel.add(card1, "Card1");
        cardPanel.add(card2, "Card2");
        cardPanel.add(card3, "Card3");

        cardLayout.show(cardPanel, "Card1");

        setLayout(new BorderLayout());
        add(cardPanel, BorderLayout.CENTER);

        JButton button1 = new JButton("Anterior");
        JButton button2 = new JButton("Tarjeta 1");
        JButton button3 = new JButton("Tarjeta 2");
        JButton button4 = new JButton("Tarjeta 3");
        JButton button5 = new JButton("Siguiente");

        button1.addActionListener(this);
        button2.addActionListener(this);
        button3.addActionListener(this);
        button4.addActionListener(this);
        button5.addActionListener(this);

        JPanel buttonPanel = new JPanel();
        buttonPanel.setLayout(new GridLayout(5, 1));
        buttonPanel.add(button1);
        buttonPanel.add(button2);
        buttonPanel.add(button3);
        buttonPanel.add(button4);
        buttonPanel.add(button5);

        // Crear el panel para los botones del Oeste
        JPanel westPanel = new JPanel();
        westPanel.setLayout(new GridLayout(5, 1));
        westPanel.add(new JButton("Botón 6"));
        westPanel.add(new JButton("Botón 7"));
        westPanel.add(new JButton("Botón 8"));
        westPanel.add(new JButton("Botón 9"));
        westPanel.add(new JButton("Botón 10"));
        // Crear el panel para el título en el Norte
        JPanel titlePanel = new JPanel();
        JLabel titleLabel = new JLabel("Título");
        titlePanel.add(titleLabel);
         // Crear el panel para el pie en el Sur
        JPanel footerPanel = new JPanel();
        JLabel footerLabel = new JLabel("Pie de página");
        footerPanel.add(footerLabel);
        
        add(buttonPanel, BorderLayout.EAST);
        add(westPanel, BorderLayout.WEST);
        add(titlePanel, BorderLayout.NORTH);
        add(footerPanel, BorderLayout.SOUTH);

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       setSize(450, 350);
        setVisible(true);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        String command = e.getActionCommand();

        switch (command) {
            case "Anterior" -> cardLayout.previous(cardPanel);
            case "Tarjeta 1" -> cardLayout.show(cardPanel, "Card1");
            case "Tarjeta 2" -> cardLayout.show(cardPanel, "Card2");
            case "Tarjeta 3" -> cardLayout.show(cardPanel, "Card3");
            case "Siguiente" -> cardLayout.next(cardPanel);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelCartas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelCartas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
