package Ejercicio12;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Aarón
 */
public class NewJFrame extends javax.swing.JFrame {

    CardLayout tarjetas;
    JPanel panelTarjetas;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        //Centro el JFrame en la pantalla
        setLocationRelativeTo(null);

        //Inicializo un border layout para el JFrame
        setLayout(new BorderLayout());

        //Creo un panel para el botón superior con fondo rojo
        JPanel panelSuperior = new JPanel();
        panelSuperior.setBackground(Color.RED);

        //Añado un botón para intercambiar tarjetas y le añado el action listener
        JButton cambiarTarjeta = new JButton("Cambiar tarjeta");
        cambiarTarjeta.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent event) {
                tarjetas.next(panelTarjetas);
            }
        });

        //Añado el botón al panel de pestañas
        panelSuperior.add(cambiarTarjeta);

        //Añado el panel de pestañas a la parte superior del JFrame
        add(panelSuperior, BorderLayout.NORTH);

        //Inicializo el layout y el panel para las tarjetas
        tarjetas = new CardLayout();
        panelTarjetas = new JPanel();
        panelTarjetas.setLayout(tarjetas);

        //Inicializo 2 tarjetas, cada una es un JPanel con un color de fondo
        JPanel primeraTarjeta = new JPanel();
        JPanel segundaTarjeta = new JPanel();
        primeraTarjeta.setBackground(Color.GREEN);
        segundaTarjeta.setBackground(Color.BLUE);

        //Añado botones a las dos tarjetas
        nuevoBoton(primeraTarjeta, "Manzanas");
        nuevoBoton(primeraTarjeta, "Naranjas");
        nuevoBoton(primeraTarjeta, "Plátanos");
        nuevoBoton(segundaTarjeta, "Lechugas");
        nuevoBoton(segundaTarjeta, "Tomates");
        nuevoBoton(segundaTarjeta, "Cebollas");

        //Añado las dos tarjetas al panel de tarjetas
        panelTarjetas.add(primeraTarjeta, "Frutas");
        panelTarjetas.add(segundaTarjeta, "Verduras");

        //Muestro la primera
        tarjetas.show(panelTarjetas, "Frutas");

        //Añado el panel de tarjetas a la parte central del border layout
        add(panelTarjetas, BorderLayout.CENTER);
    }


    //Nuevo botón
    private void nuevoBoton(JPanel panel, String titulo) {

        JButton boton = new JButton(titulo);
        panel.add(boton);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
