/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package E1;

/**
 *
 * @author Aarón
 */
public class PanelAnadir extends javax.swing.JPanel {

    private final LibreriaVisual padre;

    /**
     * Creates new form NewJPanel
     *
     * @param pad
     */
    public PanelAnadir(LibreriaVisual pad) {
        initComponents();
        this.padre = pad;
        ocultar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioGrupoMateriales = new javax.swing.ButtonGroup();
        panelComun = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        panelLibro = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtEditorial = new javax.swing.JTextField();
        panelRevista = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        btnGrabar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        radioRevista = new javax.swing.JRadioButton();
        radioLibro = new javax.swing.JRadioButton();
        txtIsbn = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        panelComun.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Autor");
        panelComun.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 26, -1, -1));

        jLabel2.setText("Titulo");
        panelComun.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, -1));

        jLabel3.setText("Año Publicacion");
        panelComun.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));
        panelComun.add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 160, 30));
        panelComun.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 180, 30));
        panelComun.add(txtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 178, 30));

        jLabel4.setText("Editorial");

        javax.swing.GroupLayout panelLibroLayout = new javax.swing.GroupLayout(panelLibro);
        panelLibro.setLayout(panelLibroLayout);
        panelLibroLayout.setHorizontalGroup(
            panelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibroLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(txtEditorial, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        panelLibroLayout.setVerticalGroup(
            panelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibroLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel5.setText("Numero");

        javax.swing.GroupLayout panelRevistaLayout = new javax.swing.GroupLayout(panelRevista);
        panelRevista.setLayout(panelRevistaLayout);
        panelRevistaLayout.setHorizontalGroup(
            panelRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRevistaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelRevistaLayout.setVerticalGroup(
            panelRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRevistaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelRevistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        radioGrupoMateriales.add(radioRevista);
        radioRevista.setText("Revista");
        radioRevista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioRevistaActionPerformed(evt);
            }
        });

        radioGrupoMateriales.add(radioLibro);
        radioLibro.setText("Libro");
        radioLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioLibroActionPerformed(evt);
            }
        });

        jLabel6.setText("ISBN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(249, 249, 249)
                            .addComponent(jLabel6)
                            .addGap(50, 50, 50)
                            .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(64, 64, 64)
                            .addComponent(panelComun, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(311, 311, 311)
                            .addComponent(radioLibro)
                            .addGap(57, 57, 57)
                            .addComponent(radioRevista)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(235, 235, 235))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(txtIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(panelComun, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioLibro)
                    .addComponent(radioRevista))
                .addGap(48, 48, 48)
                .addComponent(panelLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(panelRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGrabar)
                    .addComponent(btnVolver))
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        ocultar();
        padre.setContentPane(padre.panelPrincipal);
        padre.pack();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void ocultar() {
        this.panelLibro.setVisible(false);
        this.panelRevista.setVisible(false);
    }

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        if (radioLibro.isSelected() || radioRevista.isSelected()) {
            if (txtIsbn.getText().isBlank() || txtTitulo.getText().isBlank() || txtAutor.getText().isBlank() || txtAnio.getText().isBlank()) {
                System.out.println("Error");
            } else {
                String isbn = txtIsbn.getText();
                String titulo = txtTitulo.getText();
                String autor = txtAutor.getText();
                int anio = Integer.parseInt(txtAnio.getText());
                Material materialNuevo;
                if (radioLibro.isSelected()) {
                      String editorial = txtEditorial.getText();
                    materialNuevo = new Libro(isbn, titulo, autor, anio, editorial);
                } else {
                    int numero = Integer.parseInt(txtNumero.getText());
                    materialNuevo = new Revista(isbn, titulo, autor, anio, numero);
                }
                padre.materiales.add(materialNuevo);
                padre.recargarTabla();
                padre.setContentPane(padre.panelPrincipal);
                padre.pack();

            }

        } else {
            System.out.println("Error");
        }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void radioLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioLibroActionPerformed
        this.panelLibro.setVisible(true);
        this.panelRevista.setVisible(false);
    }//GEN-LAST:event_radioLibroActionPerformed

    private void radioRevistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioRevistaActionPerformed
        this.panelLibro.setVisible(false);
        this.panelRevista.setVisible(true);
    }//GEN-LAST:event_radioRevistaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel panelComun;
    private javax.swing.JPanel panelLibro;
    private javax.swing.JPanel panelRevista;
    private javax.swing.ButtonGroup radioGrupoMateriales;
    private javax.swing.JRadioButton radioLibro;
    private javax.swing.JRadioButton radioRevista;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtIsbn;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
