/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio14;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;

/**
 *
 * @author Aarón
 */
public class PanelBorder extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public PanelBorder() {
        initComponents();
        
        JButton button1 = new JButton("Botón 1");
        JButton button2 = new JButton("Botón 2");
        JButton button3 = new JButton("Botón 3");
        JButton button4 = new JButton("Botón 4");
        JButton button5 = new JButton("Botón 5");
        
        // Crear el panel para los botones del Este
        JPanel eastPanel = new JPanel();
        eastPanel.setLayout(new GridLayout(5, 1));
        eastPanel.add(button1);
        eastPanel.add(button2);
        eastPanel.add(button3);
        eastPanel.add(button4);
        eastPanel.add(button5);

        // Crear el panel para los botones del Oeste
        JPanel westPanel = new JPanel();
        westPanel.setLayout(new GridLayout(5, 1));
        westPanel.add(new JButton("Botón 6"));
        westPanel.add(new JButton("Botón 7"));
        westPanel.add(new JButton("Botón 8"));
        westPanel.add(new JButton("Botón 9"));
        westPanel.add(new JButton("Botón 10"));

        // Crear el panel para el título en el Norte
        JPanel titlePanel = new JPanel();
        JLabel titleLabel = new JLabel("Título");
        titlePanel.add(titleLabel);

        // Crear el panel para el pie en el Sur
        JPanel footerPanel = new JPanel();
        JLabel footerLabel = new JLabel("Pie de página");
        footerPanel.add(footerLabel);

        // Crear el JTextArea en el Centro
        JTextArea textArea = new JTextArea();

        // Configurar el BorderLayout para el JFrame
        setLayout(new BorderLayout());
        add(eastPanel, BorderLayout.EAST);
        add(westPanel, BorderLayout.WEST);
        add(titlePanel, BorderLayout.NORTH);
        add(footerPanel, BorderLayout.SOUTH);
        add(textArea, BorderLayout.CENTER);
        setSize(450, 350);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelBorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelBorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelBorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelBorder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelBorder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
