/*
 * miMarcoRaton.java
 *
 * Created on 20-ago-2010, 11:56:09
 */

package Ejercicio3;

import java.awt.event.* ;

public class miMarcoRaton extends javax.swing.JFrame {


    /** Construcor: crea nuevo marco miMarcoRaton */
    public miMarcoRaton() {
        initComponents();
        
        OyenteRaton oyenteRaton = new OyenteRaton() ;
        jButtonAceptar.addMouseListener(oyenteRaton);
        jButtonCancelar.addMouseListener(oyenteRaton);
    }

    // Implementar la clase oyente que implemente el interface MouseListener
    // Se deja en blanco el cuerpo de mouseEntered y de mouseExited, ya que
    // no nos interesan en este ejemplo. Cuando se desea escuchar algún
    // tipo de evento, de deben implementar todos los métodos del interface
    // para que la clase no tenga que ser definida como abstracta
    class OyenteRaton implements MouseListener{
        // Gestionar evento de pulsación de cualquier tecla
        @Override
        public void mousePressed(MouseEvent e) {
            escribir("Botón de ratón pulsado", e) ;      
        }
        @Override
        public void mouseReleased(MouseEvent e) {
            escribir("Botón de ratón liberado", e);
        }
        @Override
        public void mouseEntered(MouseEvent e) {
        }
        @Override
        public void mouseExited(MouseEvent e) {
        }
        @Override
        public void mouseClicked(MouseEvent e) {
            escribir("Click en el botón del ratón", e);
        }

        void escribir(String eventDescription, MouseEvent e) {
            // Escribir en el área de texto la descripción  que
            // se recibe como parámetro
            jTextArea.append(eventDescription + ".\n");

            // Comprobamos cuál de los dos botones es y lo escribimos
            if (e.getComponent().getName().equals(jButtonAceptar.getName()) )
               jTextArea.append("Es el botón Aceptar.\n");
            else
               jTextArea.append("Es el botón Cancelar.\n");
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.setName("Aceptar"); // NOI18N

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setName("Cancelar"); // NOI18N

        jTextArea.setColumns(20);
        jTextArea.setRows(5);
        jScrollPane1.setViewportView(jTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar)))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonCancelar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new miMarcoRaton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea;
    // End of variables declaration//GEN-END:variables

}
